spring:
  application:
    name: jiren-customers
  jackson:
    serialization:
      indent-output: true

  jpa:
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
 
  servlet:
    multipart:
      max-file-size: 10485760

server:
  port: 7181
  servlet:
    context-path: /customers

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: /home/diadia/logs/jiren-customers.log

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

customers:
  web:
    authorizationCookieName: auth-token
    httpOnly: true
    authorizationCookieAge: 3600
    nonAuthenticatedUrls:
      - /actuator/**
      - /v2/api-docs**
      - /v3/api-docs**
      - /swagger-ui/**
      - /swagger-resources**
      - /swagger-resources/**
      - /swagger-resources/configuration/**
      - /v1/check-user
      - /v1/documents
    authenticatedUrlPattern: /**
  batch:
      createThreads: 8

guid:
  context: 11

amazon:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    endpoint: https://s3.amazonaws.com/
    region: us-east-1
    bucket-name: katu-sandbox-assets-diadia-app
    url-obj: https://s3.amazonaws.com/katu-sandbox-assets-diadia-app/
    customersTemplateDirectory: diadia/back_office/templates/diadia/