spring:
  application:
    name: jiren-new-benefits
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true

  servlet:
    multipart:
      max-file-size: 10485760

server:
  port: 7188

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: ERROR
    com.mkyong: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: "./logs/jiren-new-benefits.log"

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

guid:
  context: 10

service:
  products: /products/{guids}
  brand-products: /brands/{brand_guids}/products
  platform-products: /platforms/{platforms_guids}/products
  category-products: /categories/{categories_guid}/products
  provider-products: /providers/{providers_guid}/products
  customers-guids: /customers/{guids}
  customers: /customers

springfox:
  documentation:
    swagger-ui:
      baseUrl: new-benefits
    swagger:
      v2:
        path: new-benefits


new-benefits:
  web:
    authorizationCookieName: auth-token
    httpOnly: true
    authorizationCookieAge: 3600
    nonAuthenticatedUrls:
      - /actuator/**
      - /v2/api-docs**
      - /v3/api-docs**
      - /new-benefits
      - /new-benefits/swagger-ui/**
      - /new-benefits/swagger-resources**
      - /new-benefits/swagger-resources/**
      - /new-benefits/swagger-resources/configuration/**
    authenticatedUrlPattern: /**
