spring:
  application:
    name: jiren-iam
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 10485760



server:
  port: 7180
  servlet:
    context-path: /iam

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: ERROR
    com.mkyong: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: "./logs/jiren-iam.log"

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

iam:
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: us-east-1
    clientId: i2bvcpp61b1dhc5rm7i7ga7rj
    userPoolId: us-east-1_iLAeJdAk7
    jwksUrl: https://cognito-idp.${iam.aws.region}.amazonaws.com/${iam.aws.userPoolId}/.well-known/jwks.json
  web:
    authorizationCookieName: auth-token
    httpOnly: true
    authorizationCookieAge: 3600
    nonAuthenticatedUrls:
      - /actuator/**
      - /v2/api-docs**
      - /v3/api-docs**
      - /swagger-ui/**
      - /swagger-resources**
      - /swagger-resources/**
      - /swagger-resources/configuration/**
      - /v1/authentication/signIn
      - /v1/users/signUp
      - /v1/password/{\\w+}/forgot
      - /v1/password/reset
      - /v1/token/refresh
    authenticatedUrlPattern: /**
  users:
    batch:
      createThreads: 8
guid:
  context: 12