spring:
  application:
    name: jiren-benefits
  jackson:
    serialization:
      indent-output: true

  jpa:
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 10485760

server:
  port: 8180

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: facele-support-security-oauth-v1
      client-secret: 36ef1c86-6c42-4e94-be7a-0697dac887c3
      production: true
    resource:
      id: jiren-benefits
      user-info-uri: ${endpoint.user-auth}
      prefer-token-info: false

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: /home/crecemas/logs/jiren-benefits.log

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

guid:
  context: 10

service:
  products: /products/{guids}
  brand-products: /brands/{brand_guids}/products
  platform-products: /platforms/{platforms_guids}/products
  category-products: /categories/{categories_guid}/products
  provider-products: /providers/{providers_guid}/products
  customers-guids: /customers/{guids}
  customers: /customers

mocks:
  enabled: false

springfox:
  documentation:
    swagger-ui:
      baseUrl: benefits
    swagger:
      v2:
        path: benefits