spring:
  application:
    name: jiren-products
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: false
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10485760
 
  kafka:
#    security:
#      protocol: "SSL"
    bootstrap-servers: localhost:9092
#    ssl:
#      trust-store-location: classpath:/client-certs/kafka.client.truststore.jks
#      trust-store-password: password
#      key-store-location:  classpath:/client-certs/kafka.client.keystore.jks
#      key-store-password: password
    consumer:
      topic: ProductTopicResp
      group-id: mygroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      topic: ProductTopicReq
      group-id: mygroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

services:
  catalog:
    product: product
    catalog: catalog

server:
  port : 9002
  
logging:
  level:
    root: INFO
    com.jiren: DEBUG
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: ../logs/jiren-customers.log

management:
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'